org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.244
loader_version_range=[1,)

mod_id=zahility
mod_name=Zahility
mod_license=All Rights Reserved
mod_version=0.1.0
mod_group_id=me.zahidkaya.zahility
