modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="specialsnowballs"
version="0.1.0"
displayName="Special Snowballs"
authors="Mehmet Zahid Kaya"
description='''
A Minecraft mod focused on unique throwable snowballs and orbs with special world interactions.
The first feature line is the Terraform Snowball family.
'''

[[dependencies.specialsnowballs]]
modId="neoforge"
type="required"
versionRange="[21.1.244,)"
ordering="NONE"
side="BOTH"

[[dependencies.specialsnowballs]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
